bgp_asn: 65001
loopback0: 10.255.1.1
p2p_links:
  - { intf: Ethernet1, ip: 10.0.0.1,  peer: spine1, peer_ip: 10.0.0.0,  peer_asn: 65100 }
  - { intf: Ethernet2, ip: 10.0.1.1,  peer: spine2, peer_ip: 10.0.1.0,  peer_asn: 65200 }
